name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: go - build
        run: go build

      - name: go - vet
        run: go vet ./...

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: release to dev
        run: echo "deploying to dev"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-dev]
    steps:
      - name: deploy to prod
        run: echo "deploying to prod"
